apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: temporary-rbac-controller-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: temporary-rbac-controller-sa
    namespace: temporary-rbac-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin #temporary-rbac-controller-role
