apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: temporary-rbac-controller
spec:
  selector:
    app: temporary-rbac-controller
  ports:
    - protocol: TCP
      port: 9443
      targetPort: 9443
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: sudorequest-mutating-webhook
  namespace: temporary-rbac-controller
webhooks:
  - name: sudorequest-annotator.tarbac.io
    admissionReviewVersions: ["v1"]
    sideEffects: None
    clientConfig:
      service:
        name: webhook-service
        namespace: temporary-rbac-controller
        path: "/mutate-v1-sudorequest"
        port: 9443
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQxekNDQXIrZ0F3SUJBZ0lVRm9jZFFRblFtNTAxQzVPUFZ2ekltdnY4Zkljd0RRWUpLb1pJaHZjTkFRRUwKQlFBd09ERTJNRFFHQTFVRUF3d3RkMlZpYUc5dmF5MXpaWEoyYVdObExuUmxiWEJ2Y21GeWVTMXlZbUZqTFdOdgpiblJ5YjJ4c1pYSXVjM1pqTUI0WERUSTBNVEl5TVRJeU1ERTFObG9YRFRJMU1USXlNVEl5TURFMU5sb3dPREUyCk1EUUdBMVVFQXd3dGQyVmlhRzl2YXkxelpYSjJhV05sTG5SbGJYQnZjbUZ5ZVMxeVltRmpMV052Ym5SeWIyeHMKWlhJdWMzWmpNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXRkcHY1ekhiejVDTQpwMTNHeHBNZzh4RjR6L3o5Ykp6VG5hYmtpVDFlQmlUWEZzZzBKRHhVaDJTbW44eUZqVjdpUEFmM1hpYklpNnltCjc3TVM2MEwwTWdjeWNhYk52L1dPdjhZakVuclpZd0piNExsVVNPTnZLSkV1ZDY4TmlhVHhjL0RmVmo3VnVwN0cKNTJXb0dNUGV3MHRVMkJzSWE2dGFuSVJEdThmZDNEUjRNVE5jV21ra2syVWJXbGNidFNhYWp0eVVEaEdhdTI0Nwpad2dBczNORWQzT21xdXhLazNrRXpqRUI4SDd5QkZiU0p5UGtVWE8wcUNQMFZZYWxRc01NQjc4bVhSM1VqdnFuCnlaQ2VpY3RqR1JYL0EwZGZFMjZmdFBrN2RVa0pRWkF6a1diQ01ydWZyTFRQWEYxUzZad3poRFR1WWVKY3NsYW4KRnkxYWRqd2E1d0lEQVFBQm80SFlNSUhWTUFrR0ExVWRFd1FDTUFBd0N3WURWUjBQQkFRREFnV2dNQk1HQTFVZApKUVFNTUFvR0NDc0dBUVVGQndNQk1JR0dCZ05WSFJFRWZ6QjlnZzkzWldKb2IyOXJMWE5sY25acFkyV0NMWGRsClltaHZiMnN0YzJWeWRtbGpaUzUwWlcxd2IzSmhjbmt0Y21KaFl5MWpiMjUwY205c2JHVnlMbk4yWTRJN2QyVmkKYUc5dmF5MXpaWEoyYVdObExuUmxiWEJ2Y21GeWVTMXlZbUZqTFdOdmJuUnliMnhzWlhJdWMzWmpMbU5zZFhOMApaWEl1Ykc5allXd3dIUVlEVlIwT0JCWUVGR0hLOSs4Qkw2ajhWZFQvSXV1bWwrb1B1R2xqTUEwR0NTcUdTSWIzCkRRRUJDd1VBQTRJQkFRQ3hPa0pzRzhZZ200Z0xKUXJsdENUQ29VdFFkRlFVbHpmSlhTWm5FVEJtSUM5MEFUWTkKOWxJUHZONFFQVCt2RWxEYk5tdVpJNGxCSlF3S0ppNG01RXBzb3ZtY2I3NEttR0dKc1JraUhXRlk0SGw2ZEcwQgpTdXFndzEwSnZqZnprWEdoTHdQdDFQTmlBajd2d2d6enF1MExSc0duSWp4dTZWVzhvN1R1Skg0MFZkbUhKUU9lClRVVmQzZ1lxRGJUM1MrL1BhS2Z2YkEvTVBadFBjQjNCRW5STU1yeXNRcjlLcFpma1NsUC9hbkxsMGtyVVp0T3oKcWl1aFRIL0s3WmxoQjVQcUVUMm11RUlKUEJjTjZGb2Y0Mk0yVFhUUFRLei9obGhhZkVURzBRUGp5OUZ4NkUyeQpIL1RxaklYb01FQi9uVHlUQzlNUUlheXZ6Mkg3dGdlcmVnN3cKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
      # openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -days 365 -nodes -subj "/CN=webhook-service.temporary-rbac-controller.svc"
      # kubectl create secret tls webhook-cert --key=key.pem --cert=cert.pem -n temporary-rbac-controller
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["tarbac.io"]
        apiVersions: ["v1"]
        resources: ["sudorequests", "clustersudorequests"]
