apiVersion: tarbac.io/v1
kind: ClusterSudoPolicy
metadata:
  name: team-a-namespaces
spec:
  maxDuration: 4h
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: cluster-admin
  allowedUsers:
    - name: test-user # Replace with your authenticated user's username 
  allowedNamespacesSelector:
    matchLabels:
      team: a