apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: get-pods-cluster-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: tarbac.io/v1
kind: ClusterTemporaryRBAC
metadata:
  name: example-cluster-temporary-rbac
spec:
  subjects:
    - kind: ServiceAccount
      name: default
      namespace: default
    - kind: ServiceAccount
      name: test
      namespace: default
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: get-pods-cluster-role
  duration: 1m
  retentionPolicy: retain

