apiVersion: tarbac.io/v1
kind: SudoPolicy
metadata:
  name: self-service-namespace-admin
  namespace: default
spec:
  maxDuration: 4h
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: cluster-admin
  allowedUsers:
    - name: masterclient
---
apiVersion: tarbac.io/v1
kind: SudoRequest
metadata:
  name: example-sudo-request
  namespace: default
spec:
  duration: "1h"
  policy: "self-service-namespace-admin"

