apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: get-pods-cluster-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: tarbac.io/v1
kind: TemporaryRBAC
metadata:
  name: example-multiple-subjects-namespaced-cluster-role
  namespace: default
spec:
  subjects:
    - kind: ServiceAccount
      name: default
      namespace: default
    - kind: ServiceAccount
      name: test
      namespace: default
  roleRef:
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    name: get-pods-cluster-role
  duration: 1m
  retentionPolicy: delete # retain

