apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sudorequests.tarbac.io
spec:
  group: tarbac.io
  names:
    kind: SudoRequest
    listKind: SudoRequestList
    plural: sudorequests
    singular: sudorequest
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                duration:
                  type: string
                  pattern: ^[0-9]+[smhd]$  # Match durations like "1h", "30m", "1d"
                  description: The duration for which the sudo access is granted.
                policy:
                  type: string
                  description: The name of the SudoPolicy to enforce for this request.
              required:
                - duration
                - policy
            status:
              type: object
              properties:
                state:
                  type: string
                  description: The state of the SudoRequest (e.g., Pending, Approved, Expired).
                createdAt:
                  type: string
                  format: date-time
                  description: When the SudoRequest was created.
                expiresAt:
                  type: string
                  format: date-time
                  description: When the SudoRequest will expire.
      additionalPrinterColumns:
        - name: State
          type: string
          description: The current state of the SudoRequest.
          jsonPath: .status.state
        - name: Created At
          type: date
          description: When the SudoRequest was created.
          jsonPath: .status.createdAt
        - name: Expires At
          type: date
          description: When the SudoRequest will expire.
          jsonPath: .status.expiresAt
      subresources:
        status: {}
