apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.webhook.certSecretName }}
  namespace: {{ .Values.namespace.name }}
type: kubernetes.io/tls
data:
  tls.crt: "" #{{ .Values.webhook.caBundle | quote }}
  tls.key: "" #{{ .Values.webhook.privateKey | quote }} # You can replace with base64-encoded key if required.
