{{- if eq (include "cert_manager_disabled" .) "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.webhook.tls.certSecretName }}
  namespace: {{ .Values.namespace.name }}
type: kubernetes.io/tls
data:
  ca.crt: ""
  tls.crt: ""
  tls.key: ""
{{- end }}
