apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: sudorequest-mutating-webhook
webhooks:
  - name: sudorequest-annotator.tarbac.io
    admissionReviewVersions: ["v1"]
    sideEffects: None
    clientConfig:
      service:
        name: {{ .Values.service.name }}
        namespace: {{ .Values.namespace.name }}
        path: "/mutate-v1-sudorequest"
        port: {{ .Values.service.port }}
      caBundle: {{ .Values.webhook.caBundle | quote }}
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["tarbac.io"]
        apiVersions: ["v1"]
        resources: ["sudorequests", "clustersudorequests"]
