apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: sudorequest-mutating-webhook
  annotations:
  {{- if include "cert_manager_enabled" . }}
    cert-manager.io/inject-ca-from: {{ .Values.namespace.name }}/{{ .Values.webhook.certManager.certName }}
  {{- end }}
webhooks:
  - name: sudorequest-annotator.tarbac.io
    admissionReviewVersions: ["v1"]
    sideEffects: None
    clientConfig:
      service:
        name: {{ .Values.service.name }}
        namespace: {{ .Values.namespace.name }}
        path: "/mutate-v1-sudorequest"
        port: {{ .Values.service.port }}
      {{- if include "ca_bundle_specified" . }}
      caBundle: {{ .Values.webhook.ca.caBundle | quote }}
      {{- end }}
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["tarbac.io"]
        apiVersions: ["v1"]
        resources: ["sudorequests", "clustersudorequests"]